from django.db import models

class Athlete(models.Model):
    id = models.IntegerField
    unique = ("id")
    # unique vs. index. We need this to be unique but not autogenerated. 
    strava_id = models.IntegerField
    unique = strava_id
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    access_token = models.CharField(max_length=200)
    def __str__(self):
        return self.id